version: "3.9"
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: era_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: